SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS F
INNER JOIN FISH_NAME_INFO AS I
ON F.FISH_TYPE = I.FISH_TYPE
WHERE (F.FISH_TYPE, LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH)
FROM FISH_INFO
GROUP BY FISH_TYPE);
